# Transcription Factor Project - KOLF2.1J Dataset Downstream Analysis
**Robin Anwyl, UCSD Subramaniam Lab**

**Goal:** Analyze the KOLF2.1J Perturb-seq dataset from the Nourreddine et al. (2024) preprint to investigate the effects of transcription factor knockdowns (TF KDs)

**Guiding Questions:** What do TF KD effects reveal about:
* the transcriptional regulatory network of hiPSCs? 
* TF crosstalk and co-regulation?
* cell lineage?
* how TFs influence chromatin remodeling?

# Import statements

Using psp_env virtual env

In [1]:
import sys
import os
psp_root = "/home/ranwyl/KOLF2.1J_Perturbation_Cell_Atlas/"
if psp_root not in sys.path:
    sys.path.insert(0, psp_root)

import psp

In [2]:
import anndata as ad
import numpy as np
import pandas as pd
import decoupler as dc
import gseapy as gp
from tqdm_joblib import tqdm_joblib
from joblib import Parallel, delayed
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("white")
from biothings_client import get_client

# Read in data

In [3]:
filepath = "/home/ranwyl/data_tf_project/KOLF_Pan_Genome_Alpha_CPMnorm_KD_ETest_Gene_gRNA25_Filtered.h5ad"
adata = psp.utils.read_anndata(filepath)
adata

AnnData object with n_obs × n_vars = 58484 × 16115
    obs: 'gRNA', 'n_gRNA', 'n_gRNA_UMIs', 'gene_target', 'celltype', 'perturbation_type', 'n_UMI_counts', 'n_genes', 'perturbed', 'channel', 'perturbation', 'gene_target_ensembl_id', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'gene_target_expression (CPM)', 'NTC_target_gene_expression (CPM)', 'target_knockdown', 'perturbation_edist', 'perturbation_pvalue', 'perturbation_significant'
    var: 'gene_ids', 'feature_types', 'n_UMI_counts', 'n_cells', 'mt', 'ribo', 'hb', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts'
    uns: 'etest_results', 'etest_results_params'
    layers: 'counts'

In [4]:
filepath_pkl = "/home/ranwyl/results_tf_project/KOLF_DE_results_KD_shrunk_4-16-26_renamed.pkl"
de_results = pd.read_pickle(filepath_pkl)
de_results.head()

,ESR2_baseMean,ESR2_log2FoldChange,ESR2_lfcSE,ESR2_stat,ESR2_pvalue,ESR2_padj,ZNF14_baseMean,ZNF14_log2FoldChange,ZNF14_lfcSE,ZNF14_stat,...,SMAD3_lfcSE,SMAD3_stat,SMAD3_pvalue,SMAD3_padj,ZNF382_baseMean,ZNF382_log2FoldChange,ZNF382_lfcSE,ZNF382_stat,ZNF382_pvalue,ZNF382_padj
A1BG,6.810465,0.494698,0.586164,1.058666,0.289752,0.999873,1.864257,0.326745,0.963938,0.621605,...,0.965429,0.529086,0.596745,0.998585,3.414072,0.340243,0.790988,0.654506,0.512786,0.99499
A1BG-AS1,1.007299,-0.410480,1.054954,-0.802323,0.422366,0.999873,0.373367,-0.507322,1.303229,-0.829939,...,1.300716,-0.804238,0.421259,0.998585,0.332644,-0.263955,1.150663,-0.562569,0.573728,0.99499
A2M,1.445779,0.351201,0.975310,0.665750,0.505571,0.999873,0.512672,-0.283313,1.178650,-0.602808,...,1.300716,-0.804238,0.421259,0.998585,0.319350,0.444568,1.667701,0.676933,0.498449,0.99499
A2ML1,3.125279,-0.210730,0.739053,-0.417188,0.676541,0.999873,0.891141,-0.208276,1.136526,-0.485204,...,1.040482,0.752123,0.451977,0.998585,1.279918,-0.287992,1.025095,-0.581470,0.560924,0.99499
A2ML1-AS1,12.835356,-0.223817,0.463001,-0.563401,0.573162,0.999873,2.926793,0.078209,0.935879,0.152192,...,0.853829,0.284118,0.776320,0.998585,2.756951,0.041142,0.791882,0.079071,0.936976,0.99499

In [5]:
leiden_clusters_filepath = "/home/ranwyl/output_files_tf_project/KOLF_leiden_clusters_4-16-26.csv"
leiden_clusters = pd.read_csv(leiden_clusters_filepath, header=0, index_col=0)
leiden_clusters.head(3)

,0,1,2,3,4,5,6,7,8,9,10,11
0,ARNT2,ADNP2,ARX,ARID3B,ASCL5,ARHGAP35,ATOH1,BBX,BCL6B,ASCL1,GLIS1,E2F7
1,ATOH7,BARX1,ATF1,BATF,ATF4,ARID2,DEAF1,BHLHE41,BHLHE40,ATF3,GPBP1L1,EBF3
2,ATOH8,CHAMP1,CDX1,FOXD1,CAMTA2,BARHL1,EOMES,CBX2,ELF4,CREBL2,GRHL2,IKZF4

In [6]:
leiden_clusters.tail(3)

         0    1    2    3    4    5    6    7    8    9   10   11
50  ZNF732  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
51  ZNF783  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
52  ZNF787  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

In [ ]:
# TF target dict

import pickle

tf_target_dict_filepath = "/home/ranwyl/reference_tf_project/tf_target_signed_interactions.pkl"
with open(tf_target_dict_filepath, 'rb') as f: # binary read mode
    tf_target_interactions_dict = pickle.load(f)

# Filter Entrez genes for Pathview (using DGE results)

In [7]:
def filter_rename_entrez_genes(de_df: pd.DataFrame) -> pd.DataFrame:
    """
    Rename genes in DGE results DF by Entrez ID and remove genes
    without an Entrez ID.
    """
    all_genes = de_df.index.tolist()
    mygene = get_client('gene')
    # Query genes by symbol and Ensembl ID
    mg_results_df = mygene.querymany(all_genes, scopes="symbol,ensemblgene",
                                     field="entrezgene", species="human",
                                     entrezonly=True, as_dataframe=True)
    # Remove duplicates
    mg_results_df = mg_results_df.loc[~mg_results_df.index.duplicated(keep=False)]
    # First set of genes to rename
    found_mg_results_df = mg_results_df[mg_results_df["entrezgene"].notna()]
    gene_entrez_rename_dict1 = found_mg_results_df["entrezgene"].to_dict()

    # Query genes that were not found by alias
    genes_not_found = mg_results_df[mg_results_df["notfound"] == True].index.tolist()
    mg_alias_results_df = mygene.querymany(genes_not_found, scopes="alias", 
                                           field="entrezgene", species="human", 
                                           entrezonly=True, as_dataframe=True)
    # Remove duplicates
    mg_alias_results_df = \
        mg_alias_results_df.loc[~mg_alias_results_df.index.duplicated(keep=False)]
    # Second set of genes to rename
    found_mg_alias_results_df = mg_alias_results_df[mg_alias_results_df["entrezgene"].notna()]
    gene_entrez_rename_dict2 = found_mg_alias_results_df["entrezgene"].to_dict()

    # Rename genes
    gene_entrez_rename_dict = gene_entrez_rename_dict1 | gene_entrez_rename_dict2
    de_df_renamed = de_df[de_df.index.isin(gene_entrez_rename_dict.keys())]
    de_df_renamed = de_df_renamed.rename(index=gene_entrez_rename_dict)
    return de_df_renamed

In [8]:
de_results.shape

(16115, 2064)

In [9]:
de_df_entrez = filter_rename_entrez_genes(de_results)

2026-04-22 16:37:01 | [WARNING] Input sequence provided is already in string format. No operation performed
2026-04-22 16:37:01 | [INFO] querying 1-1000 ...
2026-04-22 16:37:02 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-04-22 16:37:03 | [INFO] querying 1001-2000 ...
2026-04-22 16:37:04 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-04-22 16:37:05 | [INFO] querying 2001-3000 ...
2026-04-22 16:37:06 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-04-22 16:37:07 | [INFO] querying 3001-4000 ...
2026-04-22 16:37:08 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-04-22 16:37:09 | [INFO] querying 4001-5000 ...
2026-04-22 16:37:10 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-04-22 16:37:11 | [INFO] querying 5001-6000 ...
2026-04-22 16:37:12 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-04-22 16:37:13 | [INFO] querying 6001-7000 ...
2026-04-22 16:37:13 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-04-22 16:37:15 | [INFO] querying 7001-8000 ...
2026-04-22 16:37:15 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-04-22 16:37:16 | [INFO] querying 8001-9000 ...
2026-04-22 16:37:17 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-04-22 16:37:18 | [INFO] querying 9001-10000 ...
2026-04-22 16:37:19 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-04-22 16:37:20 | [INFO] querying 10001-11000 ...
2026-04-22 16:37:21 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-04-22 16:37:22 | [INFO] querying 11001-12000 ...
2026-04-22 16:37:23 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-04-22 16:37:24 | [INFO] querying 12001-13000 ...
2026-04-22 16:37:25 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-04-22 16:37:26 | [INFO] querying 13001-14000 ...
2026-04-22 16:37:27 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-04-22 16:37:28 | [INFO] querying 14001-15000 ...
2026-04-22 16:37:29 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-04-22 16:37:30 | [INFO] querying 15001-16000 ...
2026-04-22 16:37:31 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-04-22 16:37:32 | [INFO] querying 16001-16115 ...
2026-04-22 16:37:32 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-04-22 16:37:33 | [INFO] Finished.
2026-04-22 16:37:33 | [WARNING] 2 input query terms found dup hits:	[('GOLGA2P5', 2), ('TEC', 2)]
2026-04-22 16:37:33 | [WARNING] 1244 input query terms found no hit:	['ADAL', 'ARMT1', 'B3GNTL1', 'BMT2', 'BVES', 'C10orf82', 'C11orf54', 'C11orf80', 'C12orf29', 'C12orf
2026-04-22 16:37:33 | [INFO] Pass "returnall=True" to return complete lists of duplicate or missing query terms.
2026-04-22 16:37:33 | [WARNING] Input sequence provided is already in string format. No operation performed
2026-04-22 16:37:33 | [INFO] querying 1-1000 ...
2026-04-22 16:37:34 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-04-22 16:37:35 | [INFO] querying 1001-1244 ...
2026-04-22 16:37:35 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-04-22 16:37:36 | [INFO] Finished.
2026-04-22 16:37:36 | [WARNING] 5 input query terms found dup hits:	[('C17orf49', 2), ('C18orf21', 2), ('CIR1', 2), ('NDUFA4', 2), ('TDGF1', 2)]
2026-04-22 16:37:36 | [WARNING] 1113 input query terms found no hit:	['DNAJC9-AS1-1', 'ENSG00000176868', 'ENSG00000183308', 'ENSG00000197462', 'ENSG00000197585', 'ENSG00
2026-04-22 16:37:36 | [INFO] Pass "returnall=True" to return complete lists of duplicate or missing query terms.

In [10]:
de_df_entrez.shape

(14994, 2064)

In [11]:
filepath_pkl = "/home/ranwyl/results_tf_project/KOLF_DE_results_KD_shrunk_4-16-26_entrez.pkl"
de_df_entrez.to_pickle(filepath_pkl)

# TF-target dict

In [11]:
def build_tf_target_dict_signed(source_list: list[str] = ["CollecTRI", "DoRothEA", 
                                                          "TF_Perturbations_Followed_by_Expression",
                                                          "TF-LOF_Expression_from_GEO"], 
                                tfs_to_rename_dict: dict[str, list] | None = None, 
                                dorothea_levels=["A", "B", "C"]) -> dict[str, dict[str, set[str]]]:
    """
    Build dict {TF: {"UP": set of upreg genes, "DOWN": set of downreg genes}}
    using decoupler and gseapy.
    """
    all_dicts = list()

    if "CollecTRI" in source_list:
        collectri_df = dc.op.collectri(organism='human')
        collectri_dict = dict()
        for tf, gene, weight in collectri_df.iloc[:,:3].itertuples(index=False, name=None):
            if tf not in collectri_dict:
                collectri_dict[tf] = {"UP":set(), "DOWN":set()}
            if weight > 0: # TF is activator --> gene is downregulated
                collectri_dict[tf]["DOWN"].add(gene)
            else: # TF is repressor --> gene is upregulated
                collectri_dict[tf]["UP"].add(gene)
        all_dicts.append(collectri_dict)
    
    if "DoRothEA" in source_list:
        dorothea_df = dc.op.dorothea(organism='human', levels=dorothea_levels)
        dorothea_dict = dict()
        for tf, gene, weight in dorothea_df.iloc[:,:3].itertuples(index=False, name=None):
            if tf not in dorothea_dict:
                dorothea_dict[tf] = {"UP":set(), "DOWN":set()}
            if weight > 0:
                dorothea_dict[tf]["DOWN"].add(gene)
            else:
                dorothea_dict[tf]["UP"].add(gene)
        all_dicts.append(dorothea_dict)

    # Perturbation and LOF Enrichr libraries
    ko_lof_lib_list = list()
    if "TF_Perturbations_Followed_by_Expression" in source_list:
        pert_lib = gp.get_library(name="TF_Perturbations_Followed_by_Expression")
        ko_lof_lib_list.append(pert_lib)
    if "TF-LOF_Expression_from_GEO" in source_list:
        lof_lib = gp.get_library("TF-LOF_Expression_from_GEO")
        ko_lof_lib_list.append(lof_lib)
    if ko_lof_lib_list:
        ko_lof_dict = dict()
        for lib in ko_lof_lib_list:
            for tf_label, genes in lib.items():
                tf_label = tf_label.upper()
                if "HUMAN" in tf_label:
                    tf_label = tf_label.split(" ")
                    tf, reg = tf_label[0], tf_label[-1]
                    if tf not in ko_lof_dict:
                        ko_lof_dict[tf] = {"UP":set(), "DOWN":set()}
                    if reg == "UP":
                        ko_lof_dict[tf]["UP"].update(set(genes))
                    elif reg == "DOWN":
                        ko_lof_dict[tf]["DOWN"].update(set(genes))
        if tfs_to_rename_dict:
            for old_name, new_name in tfs_to_rename_dict.items():
                if new_name == "":
                    ko_lof_dict.pop(old_name)
                else:
                    ko_lof_dict[new_name] = ko_lof_dict.pop(old_name)
        all_dicts.append(ko_lof_dict)

    # Combine
    if len(all_dicts) == 1:
        return all_dicts[0]
    all_tfs = {tf for target_dict in all_dicts for tf in target_dict.keys()}
    all_tf_targets_dict = {tf: {"UP": set(), "DOWN": set()} for tf in all_tfs}
    for tf in all_tfs:
        genes_up = {g for target_dict in all_dicts if tf in target_dict for g in target_dict[tf]["UP"]}
        genes_down = {g for target_dict in all_dicts if tf in target_dict for g in target_dict[tf]["DOWN"]}
        all_tf_targets_dict[tf]["UP"].update(genes_up)
        all_tf_targets_dict[tf]["DOWN"].update(genes_down)
    return all_tf_targets_dict

In [15]:
import pickle

In [13]:
tfs_rename_dict = {"NCOA":"", "RENT1":"UPF1", "HIF2A":"EPAS1"} # old name : new name
tf_target_interactions_dict = build_tf_target_dict_signed(
    ["CollecTRI", "DoRothEA", "TF_Perturbations_Followed_by_Expression", "TF-LOF_Expression_from_GEO"], 
    tfs_to_rename_dict=tfs_rename_dict)

2026-03-05 14:31:34 | [INFO] Downloading and generating Enrichr library gene sets...
2026-03-05 14:31:54 | [INFO] Downloading and generating Enrichr library gene sets...
2026-03-05 14:32:16 | [INFO] 0017 gene_sets have been filtered out when max_size=2000 and min_size=0

Save as pickle

In [ ]:
tf_target_dict_filepath = "/home/ranwyl/reference_tf_project/tf_target_signed_interactions.pkl"
with open(tf_target_dict_filepath, 'wb') as f: # binary write mode
    pickle.dump(tf_target_interactions_dict, f)

# Cluster-level GSEA

In [50]:
def prerank_gsea_cluster_kds(
        cluster_label: int | str,
        cluster_kds: list[str], 
        DE_results: pd.DataFrame, 
        gene_set_lib: str, 
        rank_by: str="stat",
        min_term_size: int=5, 
        max_term_size: int=1000, 
        permutation_num: int=1000, 
        n_cpus_per_job: int=4,
        n_jobs: int=1,
        random_seed: int=42,
        verbose: bool=False,
        kd_col: str="KD",
        cluster_col: str="Cluster"
    ) -> pd.DataFrame:
    """
    Run pre-ranked GSEA using the given Enrichr library on each 
    individual KD in a cluster. By default, rank genes by 
    Wald test statistic. min_size and max_size control Enrichr term size.
    """
    # Helper function to run GSEA on single KD
    def process_kd(kd):
        # Rank genes for KD
        rank_df = pd.DataFrame(DE_results[f"{kd}_{rank_by}"].values,
                               columns=[rank_by],
                               index=DE_results.index)
        rank_df.dropna(axis="index", inplace=True) # Drop NaN values
        rank_df.index.name = "gene"
        rank_df.sort_values(by=rank_by, ascending=False, inplace=True)
        # Run pre-ranked GSEA
        kd_prerank_result = \
            gp.prerank(rnk=rank_df,
                        gene_sets=gene_set_lib,
                        threads=n_cpus_per_job,
                        min_size=min_term_size,
                        max_size=max_term_size,
                        permutation_num=permutation_num,
                        outdir=None,
                        seed=random_seed,
                        verbose=verbose,
                        )
        return kd_prerank_result
    
    # Run GSEA on all KDs
    if n_jobs < 1:
        raise ValueError("Invalid value for n_jobs")
    if n_jobs == 1:
        kd_prerank_results_dict = dict()
        for kd in cluster_kds:
            kd_prerank_result = process_kd(kd)
            kd_prerank_results_dict[kd] = kd_prerank_result
    else: # Run in parallel
        with tqdm_joblib(desc="Running pre-ranked GSEA", 
                         total=len(cluster_kds)):
            kd_prerank_results = Parallel(n_jobs=n_jobs)(
                delayed(process_kd)(kd) for kd in cluster_kds)
        kd_prerank_results_dict = dict(zip(cluster_kds, kd_prerank_results))
    
    # Build results DF
    prerank_res_df_list = list()
    for kd in kd_prerank_results_dict:
        # Build results DF for KD
        kd_res_df = kd_prerank_results_dict[kd].res2d.copy()
        kd_res_df.insert(0, kd_col, [kd]*kd_res_df.shape[0])
        kd_res_df.drop(columns=["Name"], inplace=True)
        prerank_res_df_list.append(kd_res_df)
    # Build results DF for cluster
    cluster_prerank_res_df = pd.concat(prerank_res_df_list)
    cluster_prerank_res_df.insert(0, cluster_col, 
                                  [cluster_label]*cluster_prerank_res_df.shape[0])
    return cluster_prerank_res_df

def prerank_gsea_all_clusters(
        cluster_df: pd.DataFrame, 
        DE_results: pd.DataFrame, 
        gene_set_lib: str, 
        min_term_size: int=5, 
        max_term_size: int=1000, 
        permutation_num: int=1000, 
        n_cpus_per_cluster: int=4, 
        n_jobs_parallel: int=10,
        random_seed: int=42, 
        verbose: bool=False,
        rank_by: str = "stat",
        ) -> pd.DataFrame:
    """
    Run pre-ranked GSEA on all KDs using the given Enrichr library.
    Build a results DF where each term is labeled by KD and cluster.
    """
    cluster_kd_dict = {cl: list(cluster_df[cl][cluster_df[cl].notna()])
                       for cl in cluster_df.columns}   
    
    with tqdm_joblib(desc="Running pre-ranked GSEA", total=len(cluster_kd_dict)):
        cluster_prerank_results = Parallel(n_jobs=n_jobs_parallel)(
            delayed(prerank_gsea_cluster_kds)(
                    cluster_label=cluster,
                    cluster_kds=cluster_kd_dict[cluster], 
                    DE_results=DE_results, 
                    gene_set_lib=gene_set_lib, 
                    rank_by=rank_by,
                    min_term_size=min_term_size, 
                    max_term_size=max_term_size, 
                    permutation_num=permutation_num, 
                    n_cpus_per_job=n_cpus_per_cluster,
                    n_jobs=1,
                    random_seed=random_seed,
                    verbose=verbose)
                for cluster in cluster_kd_dict
            )
    prerank_results_df = pd.concat(cluster_prerank_results)
    return prerank_results_df

def build_enriched_gsea_terms_df(
        prerank_results_df: pd.DataFrame,
        DE_results: pd.DataFrame,
        kd_col: str="KD",
        fdr_cutoff: float=0.05,
        fdr_col: str="FDR q-val",
        min_absolute_nes: None | float = None, 
        nes_col: str="NES",
        DE_p_threshold: float = 0.05,
        DE_p_threshold_type: str="pvalue",
        rank_by: str = "stat",
        rank_abs_threshold: int=1,
        leading_genes_col: str="Lead_genes"
    ) -> pd.DataFrame:
    """
    Subset the GSEA results DF to only enriched terms
    and add info on leading genes that are DEGs and
    that have |Wald| > 1.
    """
    # Subset to enriched terms (by FDR and NES)
    prerank_results_df = \
        prerank_results_df[prerank_results_df[fdr_col] < fdr_cutoff]
    if min_absolute_nes:
        prerank_results_df = \
            prerank_results_df[prerank_results_df[nes_col] >= min_absolute_nes]
    enriched_results_df = prerank_results_df.copy()
    
    # Add info on leading genes that pass DE significance threshold
    #   and with |rank| > rank threshold
    rank_label = "Wald" if rank_by == "stat" else rank_by
    # Build dict {KD: [DEGs]}
    kds = prerank_results_df[kd_col].unique().tolist()
    kd_DEG_dict = {kd: set(DE_results.loc[DE_results[
        f"{kd}_{DE_p_threshold_type}"] < DE_p_threshold].index)
        for kd in kds}
    # Build dict {KD: [genes with |rank| > threshold]}
    kd_rank_dict = {kd: set(DE_results.loc[abs(DE_results[
        f"{kd}_{rank_by}"]) > rank_abs_threshold].index)
        for kd in kds}
    df_leading_genes_rank_col = f"# lead genes w/ |{rank_label}| > {rank_abs_threshold}"
    # Helper function
    def _get_leading_genes_DE_rank(row):
        kd = row[kd_col]
        leading_genes = set(g for g in row[leading_genes_col].split(";"))
        de_leading = leading_genes & kd_DEG_dict.get(kd, set())
        rank_leading = leading_genes & kd_rank_dict.get(kd, set())
        return pd.Series({
            "# DE lead genes": len(de_leading),
            "DE_lead_genes": ";".join(sorted(de_leading)),
            df_leading_genes_rank_col: len(rank_leading),
            "Rank_lead_genes": ";".join(sorted(rank_leading))
        })
    # Get leading gene DE + rank info and add info to DF
    DE_rank_cols = enriched_results_df.apply(_get_leading_genes_DE_rank, axis=1)
    enriched_results_df.insert(10, "# DE lead genes", DE_rank_cols["# DE lead genes"])
    enriched_results_df.insert(11, df_leading_genes_rank_col, 
                              DE_rank_cols[df_leading_genes_rank_col])
    enriched_results_df["DE_lead_genes"] = DE_rank_cols["DE_lead_genes"]
    enriched_results_df["Rank_lead_genes"] = DE_rank_cols["Rank_lead_genes"]
    return enriched_results_df

def build_cluster_shared_gsea_terms_df(
        enriched_results_df: pd.DataFrame,
        gene_set_lib: str,
        min_cluster_kds: int=3,
        max_term_size: int=200,
        kd_col: str="KD",
        cluster_col: str="Cluster", 
        nes_col: str="NES",
        leading_genes_col: str="Lead_genes",
        DE_leading_genes_col: str="DE_lead_genes",
        rank_leading_genes_col: str="Rank_lead_genes"
        ) -> pd.DataFrame:
    """
    Given a pre-ranked GSEA results DF with enriched terms and
    info on genes that pass DE and rank thresholds, find terms 
    shared between multiple cluster KDs.
    """
    cluster_results_dfs, summary_entries = list(), list()
    # Get Enrichr library
    enrichr_lib = gp.get_library(gene_set_lib)
    # Loop through clusters
    clusters = sorted(enriched_results_df[cluster_col].unique().tolist(), key=int)
    for cl in clusters:
        # Get cluster DF
        cl_df = enriched_results_df[enriched_results_df[cluster_col] == cl]
        # Subset to shared terms
        cl_shared_terms = set(cl_df["Term"].value_counts()[
            cl_df["Term"].value_counts() >= min_cluster_kds].index)
        cl_shared_direction_terms = set()
        for term in cl_shared_terms:
            # Get only shared terms where all TF KDs have same NES sign
            cl_term_df = cl_df[cl_df['Term'] == term]
            if not (all(cl_term_df[nes_col] > 0) or all(cl_term_df[nes_col] < 0)):
                continue
            # Get only shared terms with max size
            term_size = len(enrichr_lib[term])
            if term_size > max_term_size:
                continue
            cl_shared_direction_terms.add(term)
            # Build summary entry and add to list
            term_kds = sorted(cl_term_df[kd_col].unique().tolist())
            term_lead_genes = \
                {g for genes in cl_term_df[leading_genes_col].values 
                 for g in genes.split(";")}
            term_DE_lead_genes = \
                {g for genes in cl_term_df[DE_leading_genes_col].values 
                 for g in genes.split(";")}
            term_rank_lead_genes = \
                {g for genes in cl_term_df[rank_leading_genes_col].values 
                 for g in genes.split(";")}
            summary_entries.append(
                {"Cluster": cl, "Term": term, 
                 f"# {kd_col}s": len(term_kds),
                 f"{kd_col}s": ", ".join(term_kds),
                 "Mean NES": round(cl_term_df[nes_col].mean(), 2),
                 "Term size": term_size,
                 "Total leading genes": len(term_lead_genes),
                 "Total DE leading genes": len(term_DE_lead_genes),
                 "Total leading genes > |rank threshold|": len(term_rank_lead_genes)}
                 )
        # Add cluster shared terms DF to list
        cl_df = cl_df[cl_df["Term"].isin(cl_shared_direction_terms)]
        cl_df.sort_values(by=["Term", kd_col], inplace=True)
        cluster_results_dfs.append(cl_df)
    
    # Build shared terms DF
    shared_terms_df = pd.concat(cluster_results_dfs)
    shared_terms_df.reset_index(drop=True, inplace=True)
    # Build summary DF
    summary_df = pd.DataFrame(summary_entries)
    summary_df.sort_values(by=["Mean NES", f"# {kd_col}s"], 
                           ascending=False, inplace=True)
    summary_df.reset_index(drop=True, inplace=True)

    return shared_terms_df, summary_df

## Cluster 3 (pluripotency)

In [15]:
cl3_tf_kds = list(leiden_clusters["3"][leiden_clusters["3"].notna()])
print(len(cl3_tf_kds))
print(", ".join(cl3_tf_kds))

34
ARID3B, BATF, FOXD1, GATA2, GPBP1, HES3, HMBOX1, HMX3, HNF4A, LHX1, MAFG, NANOG, NPAS4, NR1D1, PHF20, POU3F2, POU5F1, POU5F1B, RBPJ, REST, SALL4, SOX2, TBX15, ZFP92, ZNF44, ZNF136, ZNF160, ZNF396, ZNF521, ZNF540, ZNF543, ZNF597, ZNF658, ZNF853

### Hallmark

In [16]:
cl3_hallmark_results_full = prerank_gsea_cluster_kds(
    cluster_label=3,
    cluster_kds=cl3_tf_kds,
    DE_results=de_results,
    gene_set_lib="MSigDB_Hallmark_2020",
    kd_col="TF KD")

2026-04-22 16:39:07,696 [WARNING] Duplicated values found in preranked stats: 28.06% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:39:09,652 [WARNING] Duplicated values found in preranked stats: 16.57% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:39:11,575 [WARNING] Duplicated values found in preranked stats: 23.12% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:39:13,495 [WARNING] Duplicated values found in preranked stats: 26.69% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:39:15,404 [WARNING] Duplicated values found in preranked stats: 11.12% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:39:17,355 [WARNING] Duplicated values found in preranked stats: 19.43% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:39:19,287 [WARNING] Duplicated values found in preranked stats: 27.78% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:39:21,194 [WARNING] Duplicated values found in preranked stats: 27.36% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:39:23,110 [WARNING] Duplicated values found in preranked stats: 8.65% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:39:25,060 [WARNING] Duplicated values found in preranked stats: 17.60% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:39:26,992 [WARNING] Duplicated values found in preranked stats: 19.28% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:39:28,923 [WARNING] Duplicated values found in preranked stats: 21.72% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:39:30,846 [WARNING] Duplicated values found in preranked stats: 18.43% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:39:32,768 [WARNING] Duplicated values found in preranked stats: 25.82% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:39:34,679 [WARNING] Duplicated values found in preranked stats: 55.12% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:39:36,521 [WARNING] Duplicated values found in preranked stats: 52.86% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:39:38,372 [WARNING] Duplicated values found in preranked stats: 22.13% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:39:40,381 [WARNING] Duplicated values found in preranked stats: 56.04% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:39:42,211 [WARNING] Duplicated values found in preranked stats: 28.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:39:44,114 [WARNING] Duplicated values found in preranked stats: 13.40% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:39:46,051 [WARNING] Duplicated values found in preranked stats: 66.59% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:39:47,646 [WARNING] Duplicated values found in preranked stats: 54.84% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:39:49,494 [WARNING] Duplicated values found in preranked stats: 20.14% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:39:51,413 [WARNING] Duplicated values found in preranked stats: 19.34% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:39:53,352 [WARNING] Duplicated values found in preranked stats: 23.73% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:39:55,273 [WARNING] Duplicated values found in preranked stats: 25.77% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:39:57,186 [WARNING] Duplicated values found in preranked stats: 18.44% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:39:59,112 [WARNING] Duplicated values found in preranked stats: 14.49% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:40:01,049 [WARNING] Duplicated values found in preranked stats: 29.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:40:02,938 [WARNING] Duplicated values found in preranked stats: 22.67% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:40:04,863 [WARNING] Duplicated values found in preranked stats: 25.86% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:40:06,772 [WARNING] Duplicated values found in preranked stats: 20.18% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:40:08,703 [WARNING] Duplicated values found in preranked stats: 8.72% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:40:10,639 [WARNING] Duplicated values found in preranked stats: 28.99% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

In [17]:
cl3_hallmark_results_full.head(3)

,Cluster,TF KD,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,Lead_genes
0,3,ARID3B,Wnt-beta Catenin Signaling,-0.460867,-1.665677,0.013283,0.049876,0.054,13/33,17.32%,RBPJ;NKD1;NCOR2;JAG2;NUMB;ADAM17;AXIN1;CSNK1E;...
1,3,ARID3B,Fatty Acid Metabolism,0.303016,1.406668,0.014344,0.68635,0.462,32/121,18.42%,FH;GRHPR;MCEE;MLYCD;ODC1;BCKDHB;DECR1;AADAT;SL...
2,3,ARID3B,KRAS Signaling Up,-0.28692,-1.315263,0.050813,0.672858,0.737,32/112,22.69%,GLRX;ID2;CPE;PRELID3B;IKZF1;RGS16;GFPT2;NRP1;C...

In [18]:
hallmark_filepath = "/home/ranwyl/results_tf_project/KOLF_cl3_gsea_hallmark_4-22-26.pkl"
cl3_hallmark_results_full.to_pickle(hallmark_filepath)

In [19]:
cl3_hallmark_enriched = build_enriched_gsea_terms_df(
    cl3_hallmark_results_full, kd_col="TF KD",
    fdr_cutoff=0.05, min_absolute_nes=None,
    DE_results=de_results, DE_p_threshold=0.02, DE_p_threshold_type="pvalue",
    rank_by="stat", rank_abs_threshold=1
)

In [20]:
cl3_hallmark_enriched.sort_values(by="# DE lead genes", ascending=False).head()

,Cluster,TF KD,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,# DE lead genes,# lead genes w/ |Wald| > 1,Lead_genes,DE_lead_genes,Rank_lead_genes
4,3,POU5F1,Epithelial Mesenchymal Transition,0.497268,2.104242,0.0,0.0,0.0,45/145,12.66%,18,45,CADM1;FBN2;MEST;CDH2;COL11A1;SLIT2;FSTL1;RHOB;...,CADM1;CDH2;CDH6;COL11A1;COL5A2;EDIL3;FBLN1;FBN...,BASP1;CADM1;CD59;CDH11;CDH2;CDH6;COL11A1;COL1A...
12,3,POU5F1,TNF-alpha Signaling via NF-kB,0.393234,1.647028,0.0,0.012153,0.096,57/142,24.34%,12,33,HES1;RHOB;FJX1;SAT1;TNC;ABCA1;PDLIM5;GADD45A;B...,ABCA1;BTG1;FJX1;GADD45A;HES1;ID2;PDLIM5;RHOB;S...,ABCA1;ATP2B1;B4GALT1;BTG1;CCL2;CCND1;CDKN1A;CF...
8,3,POU5F1,UV Response Dn,0.429239,1.7957,0.0,0.005231,0.019,38/136,12.60%,11,38,LTBP1;ADGRL2;COL11A1;LPAR1;PTPRM;IGFBP5;PIK3R3...,ADGRL2;COL11A1;COL5A2;IGFBP5;IRS1;LPAR1;LTBP1;...,ADGRL2;AKT3;ANXA2;ARHGEF9;ATP2B1;ATP2B4;CDON;C...
11,3,POU5F1,Mitotic Spindle,0.378648,1.659641,0.0,0.011838,0.08,48/198,15.21%,9,45,PALLD;ABI1;MID1;ARHGAP5;BCL2L11;PDLIM5;ARHGAP2...,ABI1;ARHGAP29;ARHGAP5;BCL2L11;CDC42EP4;GSN;MID...,ABI1;AKAP13;APC;ARHGAP10;ARHGAP29;ARHGAP5;ARHG...
5,3,POU5F1,mTORC1 Signaling,-0.403352,-1.981094,0.0,0.000846,0.003,60/191,13.10%,7,54,CTSC;EIF2S2;HSPE1;NIBAN1;PRDX1;MCM4;POLR3G;SLC...,CTSC;EIF2S2;HSPE1;MCM4;NIBAN1;POLR3G;PRDX1,AK4;ARPC5L;ATP5MC1;CACYBP;CCT6A;CD9;CDC25A;CTH...

In [24]:
cl3_hallmark_shared_terms, cl3_hallmark_shared_terms_summary = \
    build_cluster_shared_gsea_terms_df(
        cl3_hallmark_enriched, gene_set_lib="MSigDB_Hallmark_2020",
        min_cluster_kds=3, kd_col="TF KD", max_term_size=200)

2026-04-22 16:43:08 | [INFO] Downloading and generating Enrichr library gene sets...
2026-04-22 16:43:08 | [INFO] Library is already downloaded in: /home/ranwyl/.cache/gseapy/Enrichr.MSigDB_Hallmark_2020.gmt, use local file

In [25]:
cl3_hallmark_shared_terms_degs_summary = cl3_hallmark_shared_terms_summary[
    cl3_hallmark_shared_terms_summary['Total DE leading genes'] >= 3]

In [26]:
print(f"{len(cl3_hallmark_shared_terms_summary)} shared Hallmark terms")
print(f"{len(cl3_hallmark_shared_terms_degs_summary)} shared Hallmark terms with >= 3 DE leading genes")

11 shared Hallmark terms
8 shared Hallmark terms with >= 3 DE leading genes

In [27]:
with pd.option_context('display.max_rows', None, 'display.max_colwidth', 75):
    display(cl3_hallmark_shared_terms_summary)

,Cluster,Term,# TF KDs,TF KDs,Mean NES,Term size,Total leading genes,Total DE leading genes,Total leading genes > |rank threshold|
0,3,Epithelial Mesenchymal Transition,6,"NANOG, PHF20, POU3F2, POU5F1, POU5F1B, ZNF521",1.84,200,99,21,75
1,3,UV Response Dn,6,"PHF20, POU5F1, POU5F1B, ZNF396, ZNF521, ZNF543",1.79,144,105,12,74
2,3,Allograft Rejection,3,"POU5F1, ZNF396, ZNF521",-1.61,200,55,3,40
3,3,UV Response Up,3,"NR1D1, ZNF396, ZNF521",-1.61,158,102,2,46
4,3,mTORC1 Signaling,7,"PHF20, POU3F2, POU5F1, POU5F1B, ZNF396, ZNF521, ZNF658",-1.70,200,173,9,99
5,3,E2F Targets,4,"POU5F1, POU5F1B, ZNF396, ZNF521",-1.74,200,138,5,84
6,3,DNA Repair,3,"PHF20, POU5F1, ZNF540",-1.74,150,88,2,45
7,3,Unfolded Protein Response,7,"NANOG, PHF20, POU5F1, POU5F1B, ZNF396, ZNF521, ZNF658",-1.77,113,97,2,60
8,3,Oxidative Phosphorylation,14,"GPBP1, NANOG, NR1D1, PHF20, POU5F1, POU5F1B, TBX15, ZFP92, ZNF136, ZNF3...",-1.92,200,199,3,147
9,3,Myc Targets V2,7,"NANOG, PHF20, POU3F2, POU5F1, POU5F1B, ZNF396, ZNF521",-1.95,58,54,4,30
10,3,Myc Targets V1,21,"BATF, GATA2, GPBP1, HMBOX1, NANOG, NPAS4, NR1D1, PHF20, POU3F2, POU5F1,...",-2.19,200,199,7,168

In [35]:
with pd.option_context('display.max_rows', None, 'display.max_colwidth', 75):
    display(cl3_hallmark_shared_terms_degs_summary)

,Cluster,Term,# TF KDs,TF KDs,Mean NES,Term size,Total leading genes,Total DE leading genes,Total leading genes > |rank threshold|
0,3,Epithelial Mesenchymal Transition,6,"NANOG, PHF20, POU3F2, POU5F1, POU5F1B, ZNF521",1.84,200,99,21,75
1,3,UV Response Dn,6,"PHF20, POU5F1, POU5F1B, ZNF396, ZNF521, ZNF543",1.79,144,105,12,74
2,3,Allograft Rejection,3,"POU5F1, ZNF396, ZNF521",-1.61,200,55,3,40
4,3,mTORC1 Signaling,7,"PHF20, POU3F2, POU5F1, POU5F1B, ZNF396, ZNF521, ZNF658",-1.70,200,173,9,99
5,3,E2F Targets,4,"POU5F1, POU5F1B, ZNF396, ZNF521",-1.74,200,138,5,84
8,3,Oxidative Phosphorylation,14,"GPBP1, NANOG, NR1D1, PHF20, POU5F1, POU5F1B, TBX15, ZFP92, ZNF136, ZNF3...",-1.92,200,199,3,147
9,3,Myc Targets V2,7,"NANOG, PHF20, POU3F2, POU5F1, POU5F1B, ZNF396, ZNF521",-1.95,58,54,4,30
10,3,Myc Targets V1,21,"BATF, GATA2, GPBP1, HMBOX1, NANOG, NPAS4, NR1D1, PHF20, POU3F2, POU5F1,...",-2.19,200,199,7,168

In [28]:
print(cl3_hallmark_shared_terms_degs_summary['Term'].values.tolist())

['Epithelial Mesenchymal Transition', 'UV Response Dn', 'Allograft Rejection', 'mTORC1 Signaling', 'E2F Targets', 'Oxidative Phosphorylation', 'Myc Targets V2', 'Myc Targets V1']

In [29]:
cl3_hallmark_shared_terms.head()

,Cluster,TF KD,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,# DE lead genes,# lead genes w/ |Wald| > 1,Lead_genes,DE_lead_genes,Rank_lead_genes
0,3,POU5F1,Allograft Rejection,-0.354763,-1.574622,0.009494,0.0201,0.11,29/101,18.01%,1,21,NME1;NPM1;THY1;IL27RA;TGFB1;TAP2;LY75;ABCE1;TR...,NME1,ABCE1;CAPG;EIF3D;EIF5A;ETS1;HDAC9;IL27RA;IL4R;...
1,3,ZNF396,Allograft Rejection,-0.346781,-1.606216,0.002674,0.013865,0.072,30/102,14.91%,1,18,GALNT1;NPM1;MAP4K1;UBE2N;HIF1A;NME1;LY75;MRPL3...,GALNT1,APBB1;CD74;EIF5A;GALNT1;HIF1A;IL27RA;LY75;MAP4...
2,3,ZNF521,Allograft Rejection,-0.364464,-1.640425,0.0,0.014573,0.058,26/99,13.46%,0,16,THY1;SOCS1;NME1;IL4R;IL27RA;NPM1;B2M;EIF3A;EIF...,,B2M;CCND2;CD74;CSK;DYRK3;EIF3A;EIF5A;ETS1;GCNT...
3,3,PHF20,DNA Repair,-0.346795,-1.735386,0.0,0.004074,0.017,56/143,23.62%,0,11,SUPT4H1;DGCR8;POLE4;COX17;SRSF6;TAF13;ZWINT;RF...,,COX17;DGCR8;GMPR2;POLE4;POLR2J;RFC2;SRSF6;SUPT...
4,3,POU5F1,DNA Repair,-0.345394,-1.641468,0.0,0.013299,0.065,42/145,15.09%,1,32,NME1;DUT;NME3;RRM2B;RPA3;DGCR8;APRT;POLR2I;NT5...,NME1,APRT;CDA;DGCR8;DUT;ELL;ERCC2;NME1;NME3;NME4;NT...

In [30]:
cl3_hallmark_shared_terms[
    cl3_hallmark_shared_terms['Term'] == 'Epithelial Mesenchymal Transition']

,Cluster,TF KD,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,# DE lead genes,# lead genes w/ |Wald| > 1,Lead_genes,DE_lead_genes,Rank_lead_genes
10,3,NANOG,Epithelial Mesenchymal Transition,0.374874,1.735386,0.0,0.024032,0.029,37/140,15.41%,2,24,SFRP1;VIM;CDH2;FBN2;SLIT2;TIMP3;CDH6;TPM2;MATN...,SFRP1;VIM,APLP1;CD44;CDH2;CDH6;ELN;FBN2;FSTL1;FZD8;GEM;I...
11,3,PHF20,Epithelial Mesenchymal Transition,0.408603,1.876231,0.0,0.003068,0.006,34/139,11.90%,2,21,FBN2;CADM1;SLIT2;COL11A1;CDH6;TNC;ID2;SAT1;FZD...,CADM1;FBN2,CADM1;CCN1;CDH11;CDH2;CDH6;COL11A1;COL4A1;EDIL...
12,3,POU3F2,Epithelial Mesenchymal Transition,0.37902,1.713015,0.0,0.046042,0.057,50/137,20.10%,1,17,FBN2;CDH11;CADM1;CDH6;TNC;FZD8;MYL9;GADD45A;TA...,FBN2,BMP1;CADM1;CALD1;CDH11;CDH2;CDH6;COL4A2;FBN2;F...
13,3,POU5F1,Epithelial Mesenchymal Transition,0.497268,2.104242,0.0,0.0,0.0,45/145,12.66%,18,45,CADM1;FBN2;MEST;CDH2;COL11A1;SLIT2;FSTL1;RHOB;...,CADM1;CDH2;CDH6;COL11A1;COL5A2;EDIL3;FBLN1;FBN...,BASP1;CADM1;CD59;CDH11;CDH2;CDH6;COL11A1;COL1A...
14,3,POU5F1B,Epithelial Mesenchymal Transition,0.423991,1.92752,0.0,0.008161,0.009,34/136,13.71%,2,22,FBN2;CADM1;SLIT2;CDH6;TNC;CDH2;CDH11;GADD45A;C...,CADM1;FBN2,CADM1;CDH11;CDH2;CDH6;COL11A1;COL4A2;COL5A2;ED...
15,3,ZNF521,Epithelial Mesenchymal Transition,0.374778,1.689998,0.00156,0.023386,0.063,42/141,15.23%,6,31,FBN2;CADM1;CDH2;SPP1;CDH6;FZD8;ID2;SLIT2;LAMC1...,CADM1;CDH2;CDH6;FBN2;FZD8;SPP1,BASP1;CADM1;CAP2;CDH2;CDH6;COL11A1;COL4A2;EDIL...

### GO:BP

In [52]:
cl3_gobp_results_full = prerank_gsea_cluster_kds(
    cluster_label=3,
    cluster_kds=cl3_tf_kds,
    DE_results=de_results,
    gene_set_lib="GO_Biological_Process_2025",
    kd_col="TF KD",
    n_jobs=10)

Running pre-ranked GSEA:   0%|          | 0/34 [00:00<?, ?it/s]

2026-04-22 17:52:42,249 [WARNING] Duplicated values found in preranked stats: 26.69% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:52:42,251 [WARNING] Duplicated values found in preranked stats: 16.57% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:52:42,264 [WARNING] Duplicated values found in preranked stats: 23.12% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:52:42,268 [WARNING] Duplicated values found in preranked stats: 27.36% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:52:42,283 [WARNING] Duplicated values found in preranked stats: 19.43% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:52:42,283 [WARNING] Duplicated values found in preranked stats: 27.78% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:52:42,381 [WARNING] Duplicated values found in preranked stats: 28.06% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:52:42,388 [WARNING] Duplicated values found in preranked stats: 11.12% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:52:42,399 [WARNING] Duplicated values found in preranked stats: 8.65% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:52:42,835 [WARNING] Duplicated values found in preranked stats: 17.60% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:54:19,419 [WARNING] Duplicated values found in preranked stats: 19.28% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:54:23,534 [WARNING] Duplicated values found in preranked stats: 21.72% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:54:28,208 [WARNING] Duplicated values found in preranked stats: 18.43% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:54:31,842 [WARNING] Duplicated values found in preranked stats: 25.82% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:54:36,086 [WARNING] Duplicated values found in preranked stats: 55.12% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:55:06,351 [WARNING] Duplicated values found in preranked stats: 52.86% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:55:10,568 [WARNING] Duplicated values found in preranked stats: 22.13% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:55:15,167 [WARNING] Duplicated values found in preranked stats: 56.04% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:55:19,897 [WARNING] Duplicated values found in preranked stats: 28.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:55:24,886 [WARNING] Duplicated values found in preranked stats: 13.40% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:55:57,582 [WARNING] Duplicated values found in preranked stats: 66.59% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:56:02,776 [WARNING] Duplicated values found in preranked stats: 54.84% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:56:08,893 [WARNING] Duplicated values found in preranked stats: 20.14% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:56:13,584 [WARNING] Duplicated values found in preranked stats: 19.34% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:56:18,038 [WARNING] Duplicated values found in preranked stats: 23.73% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:56:48,349 [WARNING] Duplicated values found in preranked stats: 25.77% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:56:52,849 [WARNING] Duplicated values found in preranked stats: 18.44% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:56:58,012 [WARNING] Duplicated values found in preranked stats: 14.49% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:57:03,792 [WARNING] Duplicated values found in preranked stats: 29.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:57:14,662 [WARNING] Duplicated values found in preranked stats: 22.67% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:58:06,713 [WARNING] Duplicated values found in preranked stats: 25.86% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:58:10,943 [WARNING] Duplicated values found in preranked stats: 20.18% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:58:14,809 [WARNING] Duplicated values found in preranked stats: 8.72% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:58:19,671 [WARNING] Duplicated values found in preranked stats: 28.99% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

In [53]:
cl3_gobp_results_full.head(3)

,Cluster,TF KD,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,Lead_genes
0,3,ARID3B,Endoplasmic Reticulum Tubular Network Organiza...,0.711365,2.154095,0.0,0.029179,0.031,8/17,13.03%,ZFYVE27;RTN2;REEP3;RTN4;RTN1;REEP2;RETREG3;RAB10
1,3,ARID3B,Positive Regulation of Fibroblast Migration (G...,-0.874821,-1.981664,0.0,0.793318,0.492,2/6,3.46%,THBS1;DDR2
2,3,ARID3B,Negative Regulation of Type II Interferon Prod...,-0.779967,-1.902363,0.001992,1.0,0.851,7/9,11.61%,GAS6;HAVCR2;C1QBP;RARA;CR1;HMGB1;ZC3H12A

In [54]:
gobp_filepath = "/home/ranwyl/results_tf_project/KOLF_cl3_gsea_gobp_4-22-26.pkl"
cl3_gobp_results_full.to_pickle(gobp_filepath)

In [55]:
cl3_gobp_enriched = build_enriched_gsea_terms_df(
    cl3_gobp_results_full, kd_col="TF KD",
    fdr_cutoff=0.05, min_absolute_nes=None,
    DE_results=de_results, DE_p_threshold=0.02, DE_p_threshold_type="pvalue",
    rank_by="stat", rank_abs_threshold=1
)

In [56]:
cl3_gobp_enriched.sort_values(by="# DE lead genes", ascending=False).head()

,Cluster,TF KD,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,# DE lead genes,# lead genes w/ |Wald| > 1,Lead_genes,DE_lead_genes,Rank_lead_genes
96,3,POU5F1,Nervous System Development (GO:0007399),0.407594,1.893987,0.0,0.037475,0.77,69/347,9.61%,27,69,FZD5;SOX11;ENC1;ERBB4;CDH2;HAPLN1;NRCAM;ZIC1;G...,ADGRL3;CDH2;CNTN4;EFNA5;ENC1;ERBB4;FGF8;FZD5;G...,ADGRL3;ALDH3A2;ARNT2;ATXN10;CDH2;CDK5RAP2;CDON...
84,3,POU5F1,Regulation of Cell Migration (GO:0030334),0.412982,1.913782,0.0,0.03387,0.685,115/349,20.42%,22,86,FBN2;STC1;EPHA4;ERBB4;SEMA6D;DACH1;NAV3;SLIT2;...,BMPER;CLDN4;DACH1;EPHA4;ERBB4;FBN2;FGF8;FIGNL2...,ADAM15;AFDN;AMOTL1;ANKRD44;APPL2;ARID2;ATM;BEX...
113,3,POU5F1,Central Nervous System Development (GO:0007417),0.42407,1.868205,0.0,0.049133,0.874,48/212,10.46%,19,48,EPHA7;SOX11;HAPLN1;NRCAM;ZIC1;SIX3;NRG1;CNTN4;...,AFF2;CNTN4;EPHA7;FOXG1;GRHL2;GSN;HAPLN1;HESX1;...,AFF2;ALDH3A2;AMIGO2;ARNT2;CDK5RAP2;CLASP1;CNTN...
95,3,POU5F1,Positive Regulation of Cell Differentiation (G...,0.427694,1.895027,0.0,0.037786,0.767,45/205,9.50%,19,45,FBN2;SOX5;SOX11;ZFHX3;DMD;NRCAM;MMD;FGF8;MACRO...,BMP7;BTG1;CTNNBIP1;DMD;FBN2;FGF8;FRZB;ID2;LAMB...,ARID1A;ARID1B;BMP7;BTG1;CPNE1;CTNNB1;CTNNBIP1;...
48,3,POU5F1,Generation of Neurons (GO:0048699),0.47467,1.993033,0.0,0.017611,0.286,31/131,8.79%,16,31,FZD5;SOX11;ERBB4;AUTS2;NRCAM;SIX3;GPM6A;ADGRL3...,ADGRL3;ASTN2;AUTS2;ERBB4;FZD5;FZD8;GPM6A;ID2;I...,ADGRL3;ASTN2;ATP2B4;AUTS2;EML1;ERBB4;ERCC6;FGF...

In [57]:
cl3_gobp_shared_terms, cl3_gobp_shared_terms_summary = \
    build_cluster_shared_gsea_terms_df(
        cl3_gobp_enriched, gene_set_lib="GO_Biological_Process_2025",
        min_cluster_kds=3, kd_col="TF KD", max_term_size=200)

2026-04-22 18:01:37 | [INFO] Downloading and generating Enrichr library gene sets...
2026-04-22 18:01:37 | [INFO] Library is already downloaded in: /home/ranwyl/.cache/gseapy/Enrichr.GO_Biological_Process_2025.gmt, use local file
2026-04-22 18:01:37 | [INFO] 0002 gene_sets have been filtered out when max_size=2000 and min_size=0

In [58]:
cl3_gobp_shared_terms_degs_summary = cl3_gobp_shared_terms_summary[
    cl3_gobp_shared_terms_summary['Total DE leading genes'] >= 3]

In [59]:
print(f"{len(cl3_gobp_shared_terms_summary)} shared GO:BP terms")
print(f"{len(cl3_gobp_shared_terms_degs_summary)} shared GO:BP terms with >= 3 DE leading genes")

25 shared GO:BP terms
8 shared GO:BP terms with >= 3 DE leading genes

In [60]:
with pd.option_context('display.max_rows', None, 'display.max_colwidth', 75):
    display(cl3_gobp_shared_terms_degs_summary)

,Cluster,Term,# TF KDs,TF KDs,Mean NES,Term size,Total leading genes,Total DE leading genes,Total leading genes > |rank threshold|
0,3,Eye Development (GO:0001654),4,"POU3F2, POU5F1, POU5F1B, ZNF521",2.26,58,29,8,23
1,3,Sensory Organ Development (GO:0007423),4,"PHF20, POU5F1, POU5F1B, ZNF521",2.18,74,23,7,17
2,3,Visual System Development (GO:0150063),4,"POU3F2, POU5F1, POU5F1B, ZNF521",2.11,41,15,7,13
3,3,Neuron Projection Fasciculation (GO:0106030),3,"PHF20, POU5F1, ZNF521",2.10,10,6,4,6
4,3,Response to Transforming Growth Factor Beta (GO:0071559),3,"POU3F2, POU5F1, POU5F1B",2.10,35,11,8,9
5,3,Axonal Fasciculation (GO:0007413),3,"PHF20, POU5F1, ZNF521",2.07,12,7,4,6
6,3,Regulation of Chondrocyte Differentiation (GO:0032330),3,"POU5F1, POU5F1B, ZNF521",2.07,26,17,6,12
24,3,Cytoplasmic Translation (GO:0002181),22,"BATF, FOXD1, GPBP1, HES3, HMBOX1, HMX3, HNF4A, NANOG, NR1D1, PHF20, POU...",-2.54,101,100,3,85

In [61]:
print(cl3_gobp_shared_terms_degs_summary['Term'].values.tolist())

['Eye Development (GO:0001654)', 'Sensory Organ Development (GO:0007423)', 'Visual System Development (GO:0150063)', 'Neuron Projection Fasciculation (GO:0106030)', 'Response to Transforming Growth Factor Beta (GO:0071559)', 'Axonal Fasciculation (GO:0007413)', 'Regulation of Chondrocyte Differentiation (GO:0032330)', 'Cytoplasmic Translation (GO:0002181)']

In [62]:
cl3_gobp_shared_terms.head()

,Cluster,TF KD,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,# DE lead genes,# lead genes w/ |Wald| > 1,Lead_genes,DE_lead_genes,Rank_lead_genes
0,3,PHF20,Aerobic Electron Transport Chain (GO:0019646),-0.547027,-2.353493,0.0,0.000286,0.001,32/61,24.62%,0,4,NDUFS3;NDUFA2;NDUFB10;COX6B1;NDUFA5;UQCRQ;UQCR...,,COX6B1;NDUFA2;NDUFB10;NDUFS3
1,3,POU5F1,Aerobic Electron Transport Chain (GO:0019646),-0.538348,-2.190197,0.0,0.002072,0.027,24/62,14.60%,1,20,CYCS;COX7C;UQCR10;NDUFB9;NDUFC1;COX7A2;NDUFA4;...,CYCS,COX5A;COX5B;COX6B1;COX7A2;COX7B;COX7C;CYCS;NDU...
2,3,ZNF396,Aerobic Electron Transport Chain (GO:0019646),-0.528588,-2.216433,0.0,0.00268,0.023,29/62,24.77%,0,10,NDUFA8;SLC25A51;NDUFS2;CYCS;UQCR11;UQCRC2;UQCR...,,COX6B1;CYCS;NDUFA2;NDUFA8;NDUFB4;NDUFS2;SLC25A...
3,3,ZNF44,Aerobic Electron Transport Chain (GO:0019646),-0.572365,-2.408214,0.0,0.0,0.0,28/62,17.10%,0,12,COX7A2;NDUFA7;UQCRHL;NDUFC1;NDUFB1;NDUFV2;NDUF...,,COX4I1;COX5B;COX6C;COX7A2;NDUFA7;NDUFB1;NDUFB2...
4,3,ZNF543,Aerobic Electron Transport Chain (GO:0019646),-0.548134,-2.329527,0.0,0.0,0.0,34/62,23.98%,0,12,NDUFAF1;NDUFV1;NDUFS6;NDUFS5;COX6A1;SDHAF2;UQC...,,COX6A1;COX6B1;NDUFAF1;NDUFB5;NDUFC2;NDUFS5;NDU...

### Reactome

In [31]:
cl3_reactome_results_full = prerank_gsea_cluster_kds(
    cluster_label=3,
    cluster_kds=cl3_tf_kds,
    DE_results=de_results,
    gene_set_lib="Reactome_Pathways_2024",
    kd_col="TF KD")

2026-04-22 16:43:39,904 [WARNING] Duplicated values found in preranked stats: 28.06% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

2026-04-22 16:44:19,261 [WARNING] Duplicated values found in preranked stats: 16.57% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:44:56,838 [WARNING] Duplicated values found in preranked stats: 23.12% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:45:34,533 [WARNING] Duplicated values found in preranked stats: 26.69% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:46:11,508 [WARNING] Duplicated values found in preranked stats: 11.12% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:46:49,743 [WARNING] Duplicated values found in preranked stats: 19.43% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:47:27,573 [WARNING] Duplicated values found in preranked stats: 27.78% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:48:04,521 [WARNING] Duplicated values found in preranked stats: 27.36% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:48:40,883 [WARNING] Duplicated values found in preranked stats: 8.65% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:49:19,491 [WARNING] Duplicated values found in preranked stats: 17.60% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:49:57,822 [WARNING] Duplicated values found in preranked stats: 19.28% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:50:35,832 [WARNING] Duplicated values found in preranked stats: 21.72% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:51:13,367 [WARNING] Duplicated values found in preranked stats: 18.43% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:51:55,593 [WARNING] Duplicated values found in preranked stats: 25.82% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:52:32,739 [WARNING] Duplicated values found in preranked stats: 55.12% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:53:07,393 [WARNING] Duplicated values found in preranked stats: 52.86% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:53:42,749 [WARNING] Duplicated values found in preranked stats: 22.13% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:54:20,434 [WARNING] Duplicated values found in preranked stats: 56.04% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:54:55,134 [WARNING] Duplicated values found in preranked stats: 28.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:55:31,985 [WARNING] Duplicated values found in preranked stats: 13.40% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:56:09,985 [WARNING] Duplicated values found in preranked stats: 66.59% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:56:41,596 [WARNING] Duplicated values found in preranked stats: 54.84% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:57:17,003 [WARNING] Duplicated values found in preranked stats: 20.14% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:57:54,582 [WARNING] Duplicated values found in preranked stats: 19.34% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:58:32,471 [WARNING] Duplicated values found in preranked stats: 23.73% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:59:09,889 [WARNING] Duplicated values found in preranked stats: 25.77% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 16:59:47,173 [WARNING] Duplicated values found in preranked stats: 18.44% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:00:25,268 [WARNING] Duplicated values found in preranked stats: 14.49% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:01:03,482 [WARNING] Duplicated values found in preranked stats: 29.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:01:40,625 [WARNING] Duplicated values found in preranked stats: 22.67% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:02:18,299 [WARNING] Duplicated values found in preranked stats: 25.86% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:02:55,856 [WARNING] Duplicated values found in preranked stats: 20.18% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:03:33,519 [WARNING] Duplicated values found in preranked stats: 8.72% of genes
The order of those genes will be arbitrary, which may produce unexpected results.
2026-04-22 17:04:11,999 [WARNING] Duplicated values found in preranked stats: 28.99% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

In [32]:
cl3_reactome_results_full.head(3)

,Cluster,TF KD,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,Lead_genes
0,3,ARID3B,Signaling by BMP,0.627008,2.021294,0.001953,0.134504,0.139,9/20,17.41%,SMURF1;SKI;ACVR2B;SMAD1;TGFBR3;BMPR1B;SMAD7;FS...
1,3,ARID3B,RAS Processing,-0.605594,-2.010763,0.0,0.220847,0.125,15/23,33.45%,ARL2;KRAS;ZDHHC9;PRKCQ;NRAS;GOLGA7;ABHD17A;UBA...
2,3,ARID3B,Erythropoietin Activates Phospholipase C Gamma...,0.855879,1.871523,0.0,0.483395,0.603,4/6,10.39%,LYN;IRS2;EPOR;JAK2

In [33]:
reactome_filepath = "/home/ranwyl/results_tf_project/KOLF_cl3_gsea_reactome_4-22-26.pkl"
cl3_reactome_results_full.to_pickle(reactome_filepath)

In [34]:
cl3_reactome_enriched = build_enriched_gsea_terms_df(
    cl3_reactome_results_full, kd_col="TF KD",
    fdr_cutoff=0.05, min_absolute_nes=None,
    DE_results=de_results, DE_p_threshold=0.02, DE_p_threshold_type="pvalue",
    rank_by="stat", rank_abs_threshold=1
)

In [37]:
cl3_reactome_enriched.sort_values(by="# DE lead genes", ascending=False).head()

,Cluster,TF KD,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,# DE lead genes,# lead genes w/ |Wald| > 1,Lead_genes,DE_lead_genes,Rank_lead_genes
29,3,POU5F1,Metabolism of RNA,-0.44828,-2.541102,0.0,0.0,0.0,335/698,27.00%,7,154,RPL22L1;MYC;MT-ATP6;SLIRP;SNRPN;NUP85;DDX21;PO...,DDX21;MT-ATP6;MYC;NUP85;RPL22L1;SLIRP;SNRPN,ADAR;APOBEC3C;BUD31;CNOT7;CSNK1E;CTU2;DDX21;DD...
50,3,POU5F1,Elastic Fibre Formation,0.689951,2.176287,0.0,0.004633,0.006,11/30,9.10%,5,11,FBN2;LTBP1;ITGB8;FBLN1;BMP7;ITGAV;ITGB5;LOXL1;...,BMP7;FBLN1;FBN2;ITGB8;LTBP1,BMP7;FBLN1;FBN2;FBN3;ITGAV;ITGB5;ITGB8;LOXL1;L...
62,3,POU5F1,Molecules Associated With Elastic Fibres,0.694147,2.086371,0.0,0.011969,0.025,10/25,9.10%,5,10,FBN2;LTBP1;ITGB8;FBLN1;BMP7;ITGAV;ITGB5;MFAP2;...,BMP7;FBLN1;FBN2;ITGB8;LTBP1,BMP7;FBLN1;FBN2;FBN3;ITGAV;ITGB5;ITGB8;LTBP1;M...
7,3,POU5F1,Translation,-0.556236,-2.938235,0.0,0.0,0.0,169/288,26.83%,3,70,RPL22L1;EIF2S2;TARS1;MRPL54;EIF4A1;RPL27;RPS26...,EIF2S2;RPL22L1;TARS1,DAP3;EIF1AX;EIF2B1;EIF2B3;EIF2S2;EIF3B;EIF3D;E...
172,3,POU5F1,Viral Infection Pathways,-0.310295,-1.747322,0.0,0.040231,0.935,253/692,23.96%,3,121,RPL22L1;MGAT4C;NUP85;RAC1;DUT;HSP90AB1;TUBB2B;...,MGAT4C;NUP85;RPL22L1,AP1M2;AP1S2;AP1S3;AP2S1;ATP1A2;ATP1A3;ATP1B2;A...

In [38]:
cl3_reactome_shared_terms, cl3_reactome_shared_terms_summary = \
    build_cluster_shared_gsea_terms_df(
        cl3_reactome_enriched, gene_set_lib="Reactome_Pathways_2024",
        min_cluster_kds=3, kd_col="TF KD", max_term_size=200)

2026-04-22 17:06:13 | [INFO] Downloading and generating Enrichr library gene sets...
2026-04-22 17:06:13 | [INFO] Library is already downloaded in: /home/ranwyl/.cache/gseapy/Enrichr.Reactome_Pathways_2024.gmt, use local file
2026-04-22 17:06:13 | [INFO] 0005 gene_sets have been filtered out when max_size=2000 and min_size=0

In [39]:
cl3_reactome_shared_terms_degs_summary = cl3_reactome_shared_terms_summary[
    cl3_reactome_shared_terms_summary['Total DE leading genes'] >= 3]

In [40]:
print(f"{len(cl3_reactome_shared_terms_summary)} shared Reactome terms")
print(f"{len(cl3_reactome_shared_terms_degs_summary)} shared Reactome terms with >= 3 DE leading genes")

122 shared Reactome terms
15 shared Reactome terms with >= 3 DE leading genes

In [42]:
with pd.option_context('display.max_rows', None, 'display.max_colwidth', 75):
    display(cl3_reactome_shared_terms_degs_summary)

,Cluster,Term,# TF KDs,TF KDs,Mean NES,Term size,Total leading genes,Total DE leading genes,Total leading genes > |rank threshold|
11,3,Metallothioneins Bind Metals,5,"NANOG, PHF20, POU5F1, POU5F1B, ZNF521",-1.88,11,6,3,6
72,3,Orc1 Removal From Chromatin,6,"HMBOX1, POU5F1, TBX15, ZNF396, ZNF521, ZNF597",-2.02,58,53,3,36
74,3,Host Interactions of HIV Factors,4,"POU5F1, ZNF396, ZNF521, ZNF597",-2.02,126,92,3,51
92,3,Respiratory Electron Transport,4,"PHF20, POU5F1, ZNF396, ZNF543",-2.13,158,130,3,72
94,3,Influenza Infection,20,"BATF, FOXD1, GPBP1, HES3, HMBOX1, HNF4A, NANOG, NR1D1, PHF20, POU3F2, P...",-2.23,169,153,3,119
95,3,rRNA Processing in the Nucleus and Cytosol,19,"BATF, GPBP1, HES3, HMBOX1, HNF4A, NANOG, NR1D1, PHF20, POU3F2, POU5F1, ...",-2.23,199,186,6,150
102,3,Cellular Response to Starvation,18,"BATF, FOXD1, GPBP1, HMBOX1, HMX3, NANOG, NR1D1, PHF20, POU5F1, RBPJ, TB...",-2.27,161,147,4,120
103,3,Major Pathway of rRNA Processing in the Nucleolus and Cytosol,17,"BATF, GPBP1, HMBOX1, HNF4A, NANOG, NR1D1, PHF20, POU3F2, POU5F1, POU5F1...",-2.27,189,176,5,138
104,3,Influenza Viral RNA Transcription and Replication,23,"BATF, FOXD1, GPBP1, HES3, HMBOX1, HMX3, HNF4A, NANOG, NPAS4, NR1D1, PHF...",-2.28,149,134,3,110
105,3,Regulation of Expression of SLITs and ROBOs,25,"BATF, FOXD1, GATA2, GPBP1, HES3, HMBOX1, HMX3, HNF4A, NANOG, NPAS4, NR1...",-2.32,164,152,4,127
108,3,Response of EIF2AK4 (GCN2) to Amino Acid Deficiency,28,"BATF, FOXD1, GATA2, GPBP1, HES3, HMBOX1, HMX3, HNF4A, NANOG, NPAS4, NR1...",-2.46,106,99,4,89
111,3,L13a-mediated Translational Silencing of Ceruloplasmin Expression,29,"BATF, FOXD1, GATA2, GPBP1, HES3, HMBOX1, HMX3, HNF4A, NANOG, NPAS4, NR1...",-2.52,116,109,3,100
112,3,Cap-dependent Translation Initiation,26,"BATF, FOXD1, GATA2, GPBP1, HES3, HMBOX1, HMX3, HNF4A, NANOG, NPAS4, NR1...",-2.52,124,117,3,105
113,3,Eukaryotic Translation Initiation,26,"BATF, FOXD1, GATA2, GPBP1, HES3, HMBOX1, HMX3, HNF4A, NANOG, NPAS4, NR1...",-2.52,124,117,3,105
115,3,GTP Hydrolysis and Joining of the 60S Ribosomal Subunit,27,"BATF, FOXD1, GATA2, GPBP1, HES3, HMBOX1, HMX3, HNF4A, NANOG, NPAS4, NR1...",-2.55,117,110,3,100

In [43]:
print(cl3_reactome_shared_terms_degs_summary['Term'].values.tolist())

['Metallothioneins Bind Metals', 'Orc1 Removal From Chromatin', 'Host Interactions of HIV Factors', 'Respiratory Electron Transport', 'Influenza Infection', 'rRNA Processing in the Nucleus and Cytosol', 'Cellular Response to Starvation', 'Major Pathway of rRNA Processing in the Nucleolus and Cytosol', 'Influenza Viral RNA Transcription and Replication', 'Regulation of Expression of SLITs and ROBOs', 'Response of EIF2AK4 (GCN2) to Amino Acid Deficiency', 'L13a-mediated Translational Silencing of Ceruloplasmin Expression', 'Cap-dependent Translation Initiation', 'Eukaryotic Translation Initiation', 'GTP Hydrolysis and Joining of the 60S Ribosomal Subunit']

In [44]:
cl3_reactome_shared_terms.head()

,Cluster,TF KD,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,# DE lead genes,# lead genes w/ |Wald| > 1,Lead_genes,DE_lead_genes,Rank_lead_genes
0,3,HES3,APC C Cdc20 Mediated Degradation of Mitotic Pr...,-0.453188,-1.876813,0.0,0.046639,0.541,36/62,32.63%,0,6,ANAPC11;PSMC6;ADRM1;CDC16;PSMD6;BUB3;PSMC1;ANA...,,ADRM1;ANAPC11;BUB3;CDC16;PSMC6;PSMD6
1,3,POU5F1,APC C Cdc20 Mediated Degradation of Mitotic Pr...,-0.47754,-1.964394,0.0,0.005322,0.231,30/62,24.38%,0,9,ANAPC11;PSMD7;UBE2S;PSMD11;CDC20;RPS27A;PSMA2;...,,ANAPC11;CDC20;MAD2L1;NEK2;PSMA2;PSMD11;PSMD7;R...
2,3,POU5F1B,APC C Cdc20 Mediated Degradation of Mitotic Pr...,-0.455076,-1.955582,0.0,0.014678,0.352,35/62,34.49%,0,2,PSMC4;PSMD6;ADRM1;UBE2S;PSMC2;CCNA2;ANAPC1;PSM...,,PSMC4;PSMD6
3,3,RBPJ,APC C Cdc20 Mediated Degradation of Mitotic Pr...,-0.459423,-1.914776,0.0,0.022424,0.458,27/62,28.49%,0,8,CCNA2;CDC23;PSMD7;BUB3;PSMB5;RPS27A;ANAPC11;AN...,,ANAPC11;ANAPC5;BUB3;CCNA2;CDC23;PSMB5;PSMD7;RP...
4,3,TBX15,APC C Cdc20 Mediated Degradation of Mitotic Pr...,-0.437888,-1.849982,0.0,0.03484,0.665,24/62,22.58%,0,5,PSMB3;PSMC6;PSMA2;RPS27A;PSMD8;ANAPC16;PTTG1;U...,,PSMA2;PSMB3;PSMC6;PSMD8;RPS27A